"""Argument parser for the stable Workflow Monitor CLI contract."""

from __future__ import annotations

import argparse
from pathlib import Path

from ...core.branches import ATTEMPT_STATES
from .catalog_commands import configure_catalog_parser
from .errors import WorkflowError


class WorkflowArgumentParser(argparse.ArgumentParser):
    def error(self, message: str) -> None:
        raise WorkflowError(message)

def non_negative_float(value: str) -> float:
    try:
        number = float(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("必须是数字") from exc
    if number < 0:
        raise argparse.ArgumentTypeError("必须大于或等于 0")
    return number


def add_state_arguments(parser: argparse.ArgumentParser) -> None:
    for name in ("goal", "judgment", "breakpoint", "blocker", "status", "main-goal-version"):
        parser.add_argument(f"--{name}")
    parser.add_argument("--current-step")
    parser.add_argument("--next", action="append")


def build_parser() -> argparse.ArgumentParser:
    parser = WorkflowArgumentParser(prog="workflow-monitor", add_help=False)
    parser.add_argument("-h", "--help", action="store_true", dest="basic_help")
    parser.add_argument("--help-all", action="store_true")
    parser.add_argument("--project", type=Path)
    sub = parser.add_subparsers(dest="command")
    init = sub.add_parser("init")
    init.add_argument("path", nargs="?", type=Path, default=Path("."))
    update = sub.add_parser("update")
    update.add_argument("--check", action="store_true")
    update.add_argument("--to")
    update.add_argument("--manifest-url", help=argparse.SUPPRESS)
    sub.add_parser("version")
    apply_update = sub.add_parser("_apply-update", help=argparse.SUPPRESS)
    apply_update.add_argument("--target-version", required=True)
    start = sub.add_parser("start")
    start.add_argument("task_id")
    start.add_argument("--kind", required=True, choices=("code", "docs", "review", "governance", "analysis", "design", "test", "other"))
    start.add_argument("--scope", required=True)
    start.add_argument("--out-of-scope")
    start.add_argument("--acceptance", action="append", required=True)
    start.add_argument("--task-size", choices=("small", "large"), default="small")
    start.add_argument("--git-commit", choices=("auto", "always", "never"), default="auto")
    start.add_argument("--track", choices=("stable", "research", "experiment", "sandbox"))
    start.add_argument("--topic")
    start.add_argument("--verification-profile", choices=("auto", "release"), default="auto")
    start.add_argument("--without-stage-reason")
    sub.add_parser("status")
    task = sub.add_parser("task")
    task_sub = task.add_subparsers(dest="task_command", required=True)
    recover = task_sub.add_parser("recover")
    recover.add_argument("--skip-auto-commit", action="store_true")
    recover.add_argument("--reason")
    abandon = task_sub.add_parser("abandon")
    abandon.add_argument("--reason", required=True)
    sub.add_parser("branch-status")
    sub.add_parser("prepare-pr")
    sub.add_parser("archive-attempt")
    sub.add_parser("check")
    install = sub.add_parser("install")
    install.add_argument("--force", action="store_true")
    sub.add_parser("pre-commit", help=argparse.SUPPRESS)
    context = sub.add_parser("context")
    context.add_argument("--format", choices=("markdown", "json"), default="markdown")
    diagnostics = sub.add_parser("diagnostics", help="查看或导出本地脱敏诊断")
    diagnostics_sub = diagnostics.add_subparsers(dest="diagnostics_command", required=True)
    diagnostics_sub.add_parser("status")
    diagnostics_export = diagnostics_sub.add_parser("export")
    diagnostics_export.add_argument("--output", type=Path)
    diagnostics_export.add_argument("--open-issue", action="store_true")
    diagnostics_resolve = diagnostics_sub.add_parser("resolve")
    diagnostics_resolve.add_argument("fingerprint")
    diagnostics_resolve.add_argument("--reason", required=True)
    diagnostics_sub.add_parser("cleanup")
    project = sub.add_parser("project")
    project_sub = project.add_subparsers(dest="project_command", required=True)
    project_show = project_sub.add_parser("show")
    project_show.add_argument("--format", choices=("markdown", "json"), default="markdown")
    project_update = project_sub.add_parser("update")
    project_update.add_argument("--description")
    project_update.add_argument("--big-goal")
    project_update.add_argument("--main-goal-version")
    stage = sub.add_parser("stage")
    stage_sub = stage.add_subparsers(dest="stage_command", required=True)
    stage_list = stage_sub.add_parser("list")
    stage_list.add_argument("--limit", type=int, default=20)
    stage_list.add_argument("--format", choices=("markdown", "json"), default="markdown")
    stage_show = stage_sub.add_parser("show")
    stage_show.add_argument("stage_id", nargs="?")
    stage_show.add_argument("--format", choices=("markdown", "json"), default="markdown")
    stage_start = stage_sub.add_parser("start")
    stage_start.add_argument("stage_id")
    stage_start.add_argument("--title", required=True)
    stage_start.add_argument("--goal", required=True)
    stage_start.add_argument("--acceptance", action="append", required=True)
    stage_update = stage_sub.add_parser("update")
    stage_update.add_argument("stage_id")
    stage_update.add_argument("--summary")
    stage_update.add_argument("--current-step")
    stage_update.add_argument("--next-step")
    stage_update.add_argument("--blocker")
    stage_update.add_argument("--evidence", action="append")
    stage_update.add_argument("--revision")
    stage_update.add_argument("--pause-kind", choices=("interruption", "temporary-closure"))
    stage_update.add_argument("--pause-note")
    stage_update.add_argument("--status", choices=("active", "completed", "paused", "cancelled"))
    state = sub.add_parser("state")
    state_sub = state.add_subparsers(dest="state_command", required=True)
    state_update_parser = state_sub.add_parser("update")
    add_state_arguments(state_update_parser)
    attempt = sub.add_parser("attempt")
    attempt_sub = attempt.add_subparsers(dest="attempt_command", required=True)
    attempt_sub.add_parser("show")
    attempt_update_parser = attempt_sub.add_parser("update")
    attempt_update_parser.add_argument("--hypothesis")
    attempt_update_parser.add_argument("--evidence", action="append")
    attempt_update_parser.add_argument("--conclusion")
    attempt_update_parser.add_argument("--current-step")
    attempt_update_parser.add_argument("--progress")
    attempt_update_parser.add_argument("--next-step")
    for name in ("history", "explorations"):
        query = sub.add_parser(name)
        query.add_argument("--limit", type=int, default=20)
        query.add_argument("--format", choices=("markdown", "json"), default="markdown")
    exploration = sub.add_parser("exploration")
    exploration_sub = exploration.add_subparsers(dest="exploration_command", required=True)
    exploration_import_parser = exploration_sub.add_parser("import")
    exploration_import_parser.add_argument("archive_branch")
    configure_catalog_parser(sub)
    db = sub.add_parser("db")
    db_sub = db.add_subparsers(dest="db_command", required=True)
    db_sub.add_parser("status")
    db_sub.add_parser("verify")
    db_sub.add_parser("rebuild")
    migrate = db_sub.add_parser("migrate")
    migrate.add_argument("--delete-legacy", action="store_true")
    end = sub.add_parser("end")
    end.add_argument("task_id")
    end.add_argument("--result", required=True, choices=("completed", "blocked", "failed", "indeterminate"))
    end.add_argument("--methods-action", choices=("updated", "reviewed-no-change"), help=argparse.SUPPRESS)
    end.add_argument("--main-goal", choices=("changed", "unchanged"), help=argparse.SUPPRESS)
    end.add_argument("--note", required=True)
    end.add_argument("--evidence", action="append")
    end.add_argument("--commit-message")
    end.add_argument("--attempt-state", choices=ATTEMPT_STATES)
    end.add_argument("--stage-review", choices=("updated", "reviewed-no-change"))
    add_state_arguments(end)
    return parser
